### PR TITLE
Use `lean --version` to infer filetype when `elan` is installed.

### LINKED ISSUE #88: Make standalone files use the Lean version from `elan default` when set / present
Standalone files (i.e. not part of any project structure) are assumed to always be Lean 4, regardless of whether you had set `elan default ...` to be Lean 3.

Potential fix described at #81.

### PR DESCRIPTION
**Pull request by rish987**
Closes #88, ~~failed Lean 3 stdlib ft test pending leanprover/elan#36~~. Also fixed the stdlib filetype tests.

### CODE REVIEW

**Comment by rish987** [comment]
@gebner I think there might be a slight MacOS bug with leanprover/elan#36, see test failures -- since our default toolchain in CI is Lean 3 (and the error mistook `lean` for `lean3`), I have a suspicion that it has to do with leanprover/elan#36 checking the path case-sensitively, while MacOS is has a case-insensitive (all-lowercase) filesystem.

**Comment by gebner** [comment]
> I have a suspicion that it has to do with leanprover/elan#36 checking the path case-sensitively, while MacOS has a case-insensitive (all-lowercase) filesystem.

This is a potential explanation.  But I think we need someone with access to a MacOS machine to debug this (and test the fix).

**Comment by Julian** [comment]
I have a mountain of things on my plate now for the next few days so I'm going to be quite slow at many things, but will see if I can circle back when I get a moment.

**Comment by rish987** [comment]
Nevermind Gabriel your code is good (also tested it at rish987/elan@e303f1d, let me know if that's worth upstreaming) I fixed this by `schedule_wrap`ing our `elan`- based filetype detection.

**Comment by Julian** [comment]
Can you separate (and feel free to merge separately) the unrelated changes here so it's easier to see what this does?

**Pull request merged**
