### PR TITLE
Add progress bars using the fileProgress notification.

### PR DESCRIPTION
**Pull request by gebner**

### CODE REVIEW

**Comment by gebner** [comment]
The macos build failure seems to be unrelated.

**Comment by Julian** [comment]
Yeah, the build failure is related to neovim HEAD needing tree-sitter HEAD until a tree-sitter release is out (probably by today, judging from chatter in the neovim gitter).

Will ignore it when reviewing.

And thanks! Headed out for a bit but will review later unless Rish gets to it first.

**Comment by Julian** [comment]
Looks great, thanks, merging.

**Comment by rish987** [comment]
Just tried it as well, this is awesome. Thank you!!!

**Pull request merged**
