### PR TITLE
Retry update on empty Lean 3 response in test helper.

### PR DESCRIPTION
**Pull request by rish987**
testing...

### CODE REVIEW

**Comment by rish987** [comment]
Huh, another source of flakiness after this fix is defaulting to no-widget mode (see [this run](https://github.com/Julian/lean.nvim/runs/6251632712)). I think we can just disable widgets in `contents_spec.lua`?

**Comment by Julian** [comment]
Sounds fine to me.

**Comment by rish987** [comment]
Anyone have an idea why `elan` isn't downloading in CI anymore?

**Comment by Julian** [comment]
Thanks!

**Comment by rish987** [comment]
No prob, of course continue to link me to any runs that fail unexpectedly.

**Pull request merged**
