### PR TITLE
Implement simultaneous lean3 and lean4 support with minimal lean4 syntax support.

### PR DESCRIPTION
**Pull request by rish987**
Pending neovim/nvim-lspconfig#958. (EDIT: merged)

### CODE REVIEW

**Comment by Julian** [comment]
How about the Lean 4 syntax support, I don't see that here, no?

**Comment by rish987** [comment]
Thought I'd leave that to the next PR. Though I can add it now if you'd prefer.

**Comment by Julian** [comment]
Merging this though anyhow since at the minute, we're broken due to the filetype change in lspconfig, so better half-broken than broken. But yeah as-is I think this breaks syntax highlighting for Lean 4 without tree-sitter, so we should fix that ASAP.

**Comment by rish987** [comment]
Yep on it.

**Pull request merged**
