### PR TITLE
feat(infoview): more buffer options

### LINKED ISSUE #332: Set winfixbuf when available (0.10+) on our infoview windows.
https://github.com/neovim/neovim/issues/12517

### PR DESCRIPTION
**Pull request by MithicSpirit**
Sets `nocursorcolumn`, `colorcolumn=""`, and `winfixbuf` (when available).
`'nocursorcolumn'` and `'colorcolumn'` are to prevent global options from
affecting the infoview buffer (the former is for consistency with
`'nocursorline'`, which is already present). `'winfixbuf'` is a new feature
in Neovim 0.10 that restricts the window to that particular buffer.

Closes #332.

### CODE REVIEW

**Comment by Julian** [comment]
Thanks.

0.10 has `winfixbuf` which kind of makes `bufhidden` irrelevant (as it doesn't allow the buffer to be switched). #332 is a reminder to set it.

I think we also already set `buftype`? I haven't tried in an isolated setup so it's possible it's something I do, but my infoviews are certainly already set to that. Are yours not?

I also personally don't set `colorcolumn` for any window with `buftype=nofile`, but I think it's fine to explicitly not set colorcolumn, but then why not do that directly rather than via textwidth?

The place to set it (along with any others of these we do go with) would be [here alongside the other infoview options](https://github.com/Julian/lean.nvim/blob/main/ftplugin/leaninfo.lua).

**Comment by MithicSpirit** [comment]
> 0.10 has `winfixbuf` which kind of makes `bufhidden` irrelevant (as it doesn't allow the buffer to be switched). #332 is a reminder to set it.

Good idea. Setting it now.

> I think we also already set `buftype`? I haven't tried in an isolated setup so it's possible it's something I do, but my infoviews are certainly already set to that. Are yours not?

They seem to be, but grepping for `buftype` finds no matches. I guess some function is setting automatically.

> I also personally don't set `colorcolumn` for any window with `buftype=nofile`, but I think it's fine to explicitly not set colorcolumn, but then why not do that directly rather than via textwidth?

I have `'colorcolumn'` and `'textwidth'` set globally, so it shows up independent of `'buftype'` (which is buffer-local rather than window-local anyway). I was using `'textwidth'` rather than `'colorcolumn'` because I was having issues setting window-local options (in hindsight, that's probably because of `opts`), but using the file you linked below it seems to work.

> The place to set it (along with any others of these we do go with) would be [here alongside the other infoview options](https://github.com/Julian/lean.nvim/blob/main/ftplugin/leaninfo.lua?rgh-link-date=2024-05-26T14%3A24%3A43Z).

Ah, I didn't see this. Yeah, this is a lot better.

**Comment by MithicSpirit** [comment]
Hold on while I figure out why the `'winfixbuf'` check isn't working for the macOS build.

**Comment by MithicSpirit** [comment]
Apparently 0 is truthy in Lua 🤦

**Pull request merged**
